### ISSUE TITLE
is there anyway to early release the underlying ThreadPool used by RrdNioBackend?

### ISSUE THREAD

**Issue by JerryChin** [rrd4j/rrd4j#101]
Hey buddies!

I know that RrdSyncThreadPool termination is hooked to the exit of VM, but I want to close it explicitly as my web app will be reload by the container (VM will not stop), thus cause memory leak.

Anyone can help?

**Comment by fbacchella** [comment]
Manage it by your self:
http://rrd4j.org/site/apidocs/org/rrd4j/core/RrdNioBackendFactory.html#setSyncThreadPool(org.rrd4j.core.RrdSyncThreadPool)
http://rrd4j.org/site/apidocs/org/rrd4j/core/RrdSyncThreadPool.html
