### ISSUE TITLE
Provide a means to validate rrd databases

### ISSUE THREAD

**Issue by Esnaashary** [rrd4j/rrd4j#102]
We sometimes encounter corrupt databases and would like to detect this before opening them. 

Currently, an `IOException` is thrown if validating the header fails. While we could examine the exception message (e.g. `message.contains"Invalid file header"`), we would prefer not to go down this route.

Would it be acceptable to make `Header::validateHeader()` accessible from application code? Or could rrd4j throw a distinguisable exception in this case?

**Comment by fbacchella** [comment]
There is indeed too much IOException in current code that are not real IOException. It's not possible to change that to a Rrd4JException inherited from Exception that could be checked, but from IOException that can be an idea.
But you get Invalid file header exception when the very few bytes of rrd are modified. You have a storage problem I think.

**Comment by Esnaashary** [comment]
Yes we recently have seen corrupted file and are still investigating the source of the problem. On the other end we would like to detect corrupted files in order to stash and re-create them so that the system can continue to work.

If you have any hints what could cause file corruption we would be glad to head about them. We are using the default `RrdNioBackend`.

Regarding a specific exception that indicates a corrupt header, would you accept a pull request that introduces a `CorruptHeaderException` that is inherited from `IOException` and uses this exception in `Header::validateHeader`?

**Comment by fbacchella** [comment]
I would prefer IOException -> RRD4JException -> InvalidRRD, that could be used for others corruptions cases.
