### ISSUE TITLE
The fetch data does not match the write data

### ISSUE THREAD

**Issue by ruanzy** [rrd4j/rrd4j#106]
update "d:/myrrd/demo.rrd" 1505983194:0.5636855701248357
update "d:/myrrd/demo.rrd" 1505983199:0.7841736981465633
update "d:/myrrd/demo.rrd" 1505983204:0.7775232987088528
update "d:/myrrd/demo.rrd" 1505983209:0.9040772205006345
update "d:/myrrd/demo.rrd" 1505983214:0.27094325141740705
update "d:/myrrd/demo.rrd" 1505983219:0.6164565650225645
update "d:/myrrd/demo.rrd" 1505983224:0.7806261460386432
update "d:/myrrd/demo.rrd" 1505983229:0.4647710617576658
update "d:/myrrd/demo.rrd" 1505983234:0.8515933253576786

fetch  data

fetch "d:/myrrd/demo.rrd" AVERAGE --start 1505983194 --end 1505983234
== Data fetched. 10 points obtained
                          sun
 
1505983190:               nan
1505983195: +6.7392963414E-01
1505983200: +7.8284361826E-01
1505983205: +8.0283408307E-01
1505983210: +7.7745042668E-01
1505983215: +3.4004591414E-01
1505983220: +6.4929048123E-01
1505983225: +7.1745512918E-01
1505983230: +5.4213551448E-01
1505983235:               nan

`rrdDef.addDatasource("sun", GAUGE, 2 * STEP, 0, Double.NaN);
		rrdDef.addArchive(AVERAGE, 0.5, 1, 30);// 1 step
		rrdDef.addArchive(AVERAGE, 0.5, 3, 10);// 3 steps`

**Comment by fbacchella** [comment]
rrd4j never try to store exact values.

**Comment by ruanzy** [comment]
I see，but I store int
The fetch data does not match the write data yet
