### ISSUE TITLE
Why is RrdDef#removeDatasource(String dsName) package-private?

### ISSUE THREAD

**Issue by tuxedo0801** [rrd4j/rrd4j#116]
Is there a reason for having ```RrdDef#removeDatasource(String dsName)``` package-private?

https://github.com/rrd4j/rrd4j/blob/master/src/main/java/org/rrd4j/core/RrdDef.java#L575

I have a use-case where I want to remove an data source, without killing the whole rrd ... 

br,
Alex

**Comment by fbacchella** [comment]
it's made to be used from RrdToolkit.

As a rrdDef is just a definition that some one create manually, why would like to add and then remove a data source ?

**Comment by tuxedo0801** [comment]
Ah, sorry. I see.

I had the feeling that it is possible to add and remove datasources from an existing RRD. But now it seems that this is not possible. Once RRD has been created, I cannot add or remove datasources, right?

How do I deal with changing data sources that all have the same archive setup? put each source in it's own RRD (= one DS per RrdDb) and use same same archive setup?

Or can you suggest something better?

**Comment by fbacchella** [comment]
It's not an easy task. The RRD must be duplicated, but without the removed DS.

**Comment by tuxedo0801** [comment]
ok, so I go for one RrdDb per DataSource. That's also okay.
