### ISSUE TITLE
Char arrays duplicates with ConsoleFun values in memory

### ISSUE THREAD

**Issue by macmon-secure** [rrd4j/rrd4j#123]
Hi,

we're using rrd4j to write some statistical data. In some huge installations we discovered some memory issues due to huge amounts of char array duplicates in the memory.

To initialize the archive definitions we are using e.g. `new ArcDef(ConsolFun.AVERAGE, 0.5, 1, 1440)` for various archive definitions.
In huge installations we now have the problem, that there are massive amounts of char array duplicates containing `AVERAGE` or other used `ConsoleFun` enum values.

![char_array_count](https://user-images.githubusercontent.com/16669619/50678042-27c6e700-0ffd-11e9-8731-853be231cc63.PNG)

As you can see in the screenshot (taken with the Eclipse Memory Analysis) after around 12h running our server we already have more than 434 char arrays with 'AVERAGE'
as content.

![char_array_incoming_references](https://user-images.githubusercontent.com/16669619/50678043-27c6e700-0ffd-11e9-906d-0c7302e803af.PNG)

In the second screenshot you can see from where the char array is referenced. We would recommend to use 'AVERAGE' only once as enum value if possible.

**Note:** We are using RRD4j version 3.2 and we aren't using the G1 garbage collector with _UseStringDeduplication_ parameter to eliminate this problem.

**Comment by macmon-secure** [comment]
> 
> 
> A 3.5-SNAPSHOT with some improvement on this can be found at this repository:
> 
> ```
> <snapshotRepository>
>     <id>sonatype-nexus-snapshots</id>
>     <name>Sonatype Nexus Snapshots</name>
>     <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
> </snapshotRepository>
> ```

Thanks! I'll try to test it soon.

**Comment by macmon-secure** [comment]
> 3.5-SNAPSHOT

I tested it with the 3.5-SNAPSHOT version and it works. Thank you very much for the fast fix!

**Comment by fbacchella** [comment]
Fixed in 6e6e323985da1b8dec29e62380cc55325316d269
