### ISSUE TITLE
RRD4j 3.4 increasing number of open files

### ISSUE THREAD

**Issue by epraja** [rrd4j/rrd4j#124]
Hi, i recently upgrade the version of rrd4j in a project from 3.3.1 to 3.4 and start to have increasing number of open files.
In attach i provide a test case.

Test using lsof.
lsof -u <user> | uniq | grep "/tmp/test.rrd" | wc -l

[RRDTest.zip](https://github.com/rrd4j/rrd4j/files/2787961/RRDTest.zip)

**Comment by fbacchella** [comment]
On what JVM ?

**Comment by epraja** [comment]
java version "1.8.0_161"

**Comment by fbacchella** [comment]
With 
```
        RrdBackendFactory.setActiveFactories(new RrdRandomAccessFileBackendFactory());
```
there is no problems.

Using the default backend (RrdNioBackend) with:
```
        RrdBackendFactory.setActiveFactories(new RrdNioBackendFactory(0));
```

There is the problem. Performing a gc release open files. So I think the release trick I was supposed to used failed.

**Comment by fbacchella** [comment]
Fixed in f34d983.

But build of a snapshot version is failing because of https://bugs.openjdk.java.net/browse/JDK-8212233.

**Comment by epraja** [comment]
Hi , can you provide a patch version with this fix?

**Comment by fbacchella** [comment]
I will try to do that very soon. The failling snapshot is now fixed anyway.
