### ISSUE TITLE
Add support for image data URL in setBackgroundImage and setOverlayImage

### ISSUE THREAD

**Issue by hbs** [rrd4j/rrd4j#136]

**Comment by fbacchella** [comment]
It should be done in 00030c27ef0d21576196e47165c08ce16fa3b899.

**Comment by hbs** [comment]
Does it work with data:image/png;base64,... URLs?

**Comment by fbacchella** [comment]
it works on any URL that Java's URL can handle and provides a stream for. But any way, you can play with ImageSource (https://github.com/rrd4j/rrd4j/commit/00030c27ef0d21576196e47165c08ce16fa3b899#diff-a7218a92681936e80ce2741ca3551f65R58) and provide image with any source you want. https://github.com/geosolutions-it/imageio-ext can help too as it provides implementation of https://docs.oracle.com/javase/7/docs/api/javax/imageio/spi/ImageInputStreamSpi.html.

**Comment by fbacchella** [comment]
Fixed in 3.7
