### ISSUE TITLE
Setting graph property "start" seems broken in 3.7

### ISSUE THREAD

**Issue by matthiasjordan** [rrd4j/rrd4j#141]
# How to repro
I have code that basically follows the JavaDoc of RrdGraphDefTemplate:

```
RrdGraphDefTemplate t = new RrdGraphDefTemplate(new InputSource(is));
t.setVariable("start", new GregorianCalendar(2020, 2, 25));
...
RrdGraphDef gdef = t.getRrdGraphDef();
```
The XML in the input source to the constructor above also follows the above mentioned JavaDoc.

# Observed behavior
An exception occurs:
```
java.lang.IllegalArgumentException Unparsable time null
at org.rrd4j.core.timespec.TimeParser.parse(TimeParser.java375)
at org.rrd4j.core.Util.getTimestamp(Util.java280)
at org.rrd4j.graph.RrdGraphDefTemplate.lambda$getRrdGraphDef$1(RrdGraphDefTemplate.java317)
at org.rrd4j.graph.RrdGraphDefTemplate.getRrdGraphDef(RrdGraphDefTemplate.java319)
```

# Hints
* The code in question used to work up to RRD4J 3.6. (After noticing an error in my testing/debugging, I made sure that this is true, and it really did work up until 3.6.)
* When I replace `<start>${start}</start>` with `<start>now - 1d</start>` the whole thing works.
* When I use `<start>${starttt}</start>` with `t.setVariable("starttt",...)` the same problem occurs, suggesting it is not the variable name that causes the problem.
* Setting other graph properties seems to work - e.g. when I set `width` to 2000 and have XML like `<width>${width}</width>` the graph will be about 2000 pixels wide.

**Comment by matthiasjordan** [comment]
Thanks for fixing this!

**Comment by fbacchella** [comment]
Version 3.8 is published, that fixes that bug.
