### ISSUE TITLE
Unable to delete the image file

### ISSUE THREAD

**Issue by Taiguofen** [rrd4j/rrd4j#144]
RrdGraph graph = new RrdGraph(gDef); // will create the graph in the path specified
			
	   byte[] graphBytes = graph.getRrdGraphInfo().getBytes();//InputStream not close
			
            File file = new File(imageFileName);
            boolean result = file.delete();
            logger.info("delete file: "+result);//false

**Comment by fbacchella** [comment]
Indeed. The stream is open in the constructor, that’s not a good idea. Let me have a look to fixe that in an efficient way. Perhaps RrdGraph should be made closeable.

**Comment by fbacchella** [comment]
Release 2.8.1 fixes this issue.

**Comment by Taiguofen** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
