### ISSUE TITLE
Unbounded growth of rrd4j storage file

### ISSUE THREAD

**Issue by Toparvion** [rrd4j/rrd4j#163]
We are using rrd4j v3.9 in a quite heavy loaded project where several thousands databases are created as local files with `org.rrd4j.core.RrdRandomAccessFileBackend`. A small part of them are updated once per 30 seconds, the rest are updated much rarely, from 5 minutes to 24 hours.

The RRD4J database is loaded with code like (wrapped into `try-with-resources` section):
```java
    RrdDb db = RrdDb.getBuilder()
        .usePool()
        .setReadOnly(isReadOnly)
        .setPath(dbPath)
        .setBackendFactory(backendFactory)
        .build();
```
, i.e. with no pool customization or other tuning.

From time to time we observe that the files grow in size unpredictably. The listing below contains entries from 18 Mb to 1.5 Gb:
```
-rw-r--r--   1 root      root    42535664 Feb 29 21:42 users.admin.devices.avatar_1683211596583.IF_ifXTable.ifInBroadcastPkts.rrd
-rw-r--r--   1 root      root  1614935380 Feb 29 21:56 users.admin.devices.avatar_1683895164333.IF_ifXTable.ifInBroadcastPkts.rrd
-rw-r--r--   1 root      root    18545468 Feb 29 21:52 users.admin.devices.avatar_1684160909693.IF_ifXTable.ifOutOctets.rrd
-rw-r--r--   1 root      root   127984804 Feb 29 21:54 users.admin.devices.avatar_1684163574962.IF_ifXTable.ifInMulticastPkts.rrd
-rw-r--r--   1 root      root    60115764 Feb 29 21:56 users.admin.devices.avatar_1684264372867.IF_ifXTable.ifInMulticastPkts.rrd
-rw-r--r--   1 root      root    38503852 Feb 29 21:56 users.admin.devices.avatar_1684264979357.IF_ifXTable.ifInBroadcastPkts.rrd
-rw-r--r--   1 root      root    19859792 Feb 29 21:40 users.admin.devices.avatar_1684265605798.IF_ifXTable.ifInBroadcastPkts.rrd
-rw-r--r--   1 root      root   116297508 Feb 29 21:54 users.admin.devices.avatar_1685151877065.IF_ifXTable.ifInBroadcastPkts.rrd
```
Though the numbers of datasources, archives and samples in each of them stay the same:
![image](https://github.com/rrd4j/rrd4j/assets/12630412/13e99b0b-fad7-46dc-aa9c-dc2ca5216480)

The sample of an over-grown file (1.5 GB) is attached: 
[users.admin.devices.avatar_1683895164333.IF_ifXTable.ifInBroadcastPkts.zip](https://github.com/rrd4j/rrd4j/files/14456565/users.admin.devices.avatar_1683895164333.IF_ifXTable.ifInBroadcastPkts.zip)

Other details may also be provided if needed.

Is it a consequence of the tool misusing or a bug in it?

**Comment by fbacchella** [comment]
That's a misusing. rrd file are fixed size by design.

**Comment by fbacchella** [comment]
Why are you using one rrd for each metrics ? In the example rrd, I see 3 datastores, 99356, 99355 and 99354. What are they for ?

**Comment by Toparvion** [comment]
@fbacchella , 
> Why are you using one rrd for each metrics ?
Because each file represents a set of metrics for a hardware device. And since those devices are independent of each other, their statistics databases are isolated as well; they can be even stored separately (on different disks).

> I see 3 datastores, 99356, 99355 and 99354. What are they for ?
The devices whose metrics are stored in rrd files are network control nodes such as switches and routers. The figures above represent the IDs of the physical ports of the devices. The actual set of datastores (and their names) is completely defined by the device and may vary from a couple to several hundreds of ports.

**Comment by Toparvion** [comment]
> That's a misusing. 

Could you please elaborate on this? What is particularly wrong with storing statistics in separate files for each device and why does it cause problems in such rare cases?

**Comment by fbacchella** [comment]
It’s interesting to put together values that are collected or displayed at the same time, it saves IO as an update of many metrics can be done with only 2 IO.
It’s also interesting to pack metrics for a device together and store only that device in a given rrd, so when you remove it, you just have to remove the rrd.
But of course, than might not fit well your use case.

**Comment by Toparvion** [comment]
@fbacchella , thank you for the suggestions!

> put together values that are collected or displayed at the same time

This one is unfortunately not achievable in that particular project because the entire architecture is built upon separating the statistics by devices, not by time.


> pack metrics for a device together and store only that device in a given rrd

If I understood correctly, this is what we already do: storing each device's metrics in its own RRD file. The file then contains (usually) 3 archives in each of several datastores (by one for each device port).
How does this suggestion differ from the use case I've described initially?

**Comment by fbacchella** [comment]
My own monitoring tool (https://github.com/fbacchella/jrd) uses one rrd by device and by interface. At each round of collect, it reads all metrics for that at the same time and store that values in one one single update. That's very different from your architecture, where you store many interfaces for a given metric for a given host in the same rrd.

**Comment by Toparvion** [comment]
@fbacchella, thanks for the reference! 
Looking at the JRDS's [RrdDbStore.commit()](https://github.com/fbacchella/jrds/blob/f5ca026afb58f5d978e0447a513b0f2341bf3b5c/jrds-core/src/main/java/jrds/store/RrdDbStore.java#L298) method and its invocation paths, I still see a very similar logic to the one implemented in our project. Perhaps, the main difference is in the metrics – we treat them on a higher level than interfaces and therefore make the metrics include the interfaces (datasources), but not vice versa. We’ll discuss an alternative approach based on your experience.

However, it still doesn’t explain why the current approach causes RRD files to grow. Is there a way to figure out the reason and prevent it from happening in future?

**Comment by fbacchella** [comment]
As I explained, rrd can’t grow. They are created initialy with a given size and that never change. That size depends of the number of datasource and the archive definition.

**Comment by Toparvion** [comment]
Ok, we'll try to find out the root cause of the growth in our business logic and, if successfully, I'll describe it here for someone else facing the same issue.

**Comment by Toparvion** [comment]
What I've found out so far is that the growth is caused not by the archives themselves (the robins have fixed-size indeed) but by huge tails of zeros at the end of the problematic RRD files.

In most cases, those tails end with 8 non-zero bytes like:
```
40 20 A0 6D 3A 06 D3 A0 (for 18 Mb file)
7F F8 00 00 00 00 00 00 (for 122 Mb file)
40 25 10 62 4D D2 F1 AA (for 1.5 Gb file)
```
(all the files have size about several dozens of kilobytes before that explosive growth)

Just for an experiment, I've removed the zero tail in a 18 Mb-long file thus reducing it to 36.6 Kb. After that the file remained correct for opening in RRD Tool Inspector, all the observable data stayed the same, no changes were noticed. It looks confirming that the file pollution comes neither from incorrect database declaration, nor from the data it stores.
The example of the file before and after reducing can be found here: [rrd.zip](https://github.com/rrd4j/rrd4j/files/14518778/rrd.zip)

@fbacchella , do you have any ideas on what can be the source of such a "zero pollution"? Or could you suggest a diagnostic that I should add to figure it out? (besides changing the architecture)

**Comment by Toparvion** [comment]
I've tried to search for this sequence by myself and asked the engineers who work with the system closer than me, but nothing similar was found.
I've also noticed that the second sequence (`7F F8 00 00 00 00 00 00`) appears among over-sized files a bit more often than others. The value itself doesn't tell me anything meaningful (including attempts to treat it as a part of some bigger sequence or as a combination of smaller values). However, it seems sensible to try to find out a bit more about it.

**Comment by fbacchella** [comment]
Is your JVM version up to date ? Your OS ?

**Comment by Toparvion** [comment]
> 7F F8 00 00 00 00 00 00 is the representation of NaN.

Thank you for pointing to this! I didn't notice it, though it could be a clue since NaN is something I can search for in other statistics datasets.

> Is your JVM version up to date ? Your OS ?

The major version of JVM is quite old (8) but the build is relatively fresh:
```
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
```
The distribution is Liberica JDK from BellSoft.

As of OS:
```
NAME="Oracle Linux Server"
VERSION="8.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.4"
```

There is an ongoing work on upgrading the JDK in this project to a more recent version, though I'm not sure it will be finished soon. Anyway, thanks for your help!
We'll keep monitoring new occurrences of the issue and try to figure out the root cause by revealing their correlation with other processes within the application.

**Comment by Toparvion** [comment]
Yes, you're right. However, this is a customer's server and thus its OS is out of our control. We can ask the customer to upgrade only if we're pretty sure that it will solve the problem.

**Comment by Toparvion** [comment]
The issue was workaround'ed by leveraging a `ReentrantReadWriteLock` on each session of `Statistics` instance interaction.  Depending on the type of interaction - either reading or read/write - the lock is taken as `read` or `write` accordingly. While slightly reduced the overall module throughput (quite acceptable though), this solution helped to avoid the issue, and we haven't faced it for several months since then.
