### ISSUE TITLE
bug in fetchData.exportXml() = exportXml(OutputStream outputStream) = writer.writeComment(Util.getDate(timestamps[i])) = does not take time-zone offset

### ISSUE THREAD

**Issue by harp077** [rrd4j/rrd4j#169]
Good day !
First of all, thank you very much for your excellent work !
I wanted to report about one small mistake - but for many it is very important !
code:
RrdDb rrdDb = ......
FetchRequest fetchRequest = rrdDb.createFetchRequest(ConsolFun.AVERAGE, run, end);
FetchData fetchData = fetchRequest.fetchData();

fetchData.exportXml(); //BUG in exportXml(OutputStream outputStream)=writer.writeComment(Util.getDate(timestamps[i])) =does not take time-zone offset ! The error is only in this line - everything else is absolutely correct ! Error only in comment !

fetchData.dump();  // time-zone offset take well !
rrdDb.exportXml(); // time-zone offset take well !
rrdDb.dump();        // time-zone offset take well !

With best regards, Roman Koldaev

**Comment by fbacchella** [comment]
I don’t get your problem and what exactly do you expect ? fetchData.exportXml() extract start and end time from the FetchRequest that expect 2 long, that represent a number of seconds from Epoch, when created in RrdDb.createFetchRequest.

**Comment by harp077** [comment]
Please try any simple example with time-zone offset and you will see this error immediately

**Comment by harp077** [comment]
Here is an example of a selection from the same file
![git-02](https://github.com/user-attachments/assets/5ffbf93c-f68f-4b60-84ff-7aa727d38466)
![git-01](https://github.com/user-attachments/assets/04b5bd25-1858-43f1-a774-c4cf56a043c9)

**Comment by harp077** [comment]
You can see that:

- fetchData.exportXml();  = with bug in line "writer.writeComment(Util.getDate(timestamps[i]));" in exportXml(OutputStream outputStream)

- rrdDb.exportXml();  = is right

**Comment by fbacchella** [comment]
Can you please provides text snipped insteaf of unuseable screen shot ? I can’t see anything. Just  two lines of plain text, one with what you see and one with what you expect ?

**Comment by harp077** [comment]
1 snap - it is rrdDb.exportXml(); = is right
2 snap - it is fetchData.exportXml(); = with bug
i am prepare text for you later

**Comment by harp077** [comment]
I made small maven example for you:

[rrd4j-fetch-timezone-offset-demo.zip](https://github.com/user-attachments/files/16573999/rrd4j-fetch-timezone-offset-demo.zip)

Many thanks in advance !
Best regards, harp07.

**Comment by fbacchella** [comment]
And what I am expected to do with your project ?

I don’t understand why you can’t explain plain things with plain words.

The formatted time stamps are both right, but not formatted in the same way.

This commit should solve your problem. https://github.com/rrd4j/rrd4j/commit/8d596d602b0e2ac540817e308f89cac3652fc0de

**Comment by harp077** [comment]
Thanks !
But i can't compile project rrd4j - because compile error:

com/tomgibara/crinch/hashing/PerfectStringHash.java:[235,12] error: variable s1 might not have been initialized

**Comment by fbacchella** [comment]
It works with CirlceCI build, see https://app.circleci.com/pipelines/github/rrd4j/rrd4j/170/workflows/65d5afc1-68ff-4406-9afa-8810178eeb40

**Comment by harp077** [comment]
Many thanks !
And where can I download the latest rrd4j.jar with these fixes ?

**Comment by fbacchella** [comment]
Yes it’s good.

**Comment by harp077** [comment]
I checked this
Unfortunately, it turned out even worse - now it's generally wrong everywhere, i'am sorry (((((

**Comment by fbacchella** [comment]
It’s not wrong, it’s different from what you expect. Look at the patch, you can now provide a XmlWriter with a DateTimeFormater that fits your needs.

**Comment by harp077** [comment]
Understood, thank you very much !
Could you make the design for convenience:

XmlWriter xmlWriter = XmlWriter.getInstanceWithTimeZone(ZoneId zid)

??
