### ISSUE TITLE
Adding Cassandra backend support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rrd4j/rrd4j#20]
```
Hi,

as with the MongoDB support, support for Apache Cassandra, a Java based "NoSQL" 
engine would be great. 

```

Original issue reported on code.google.com by `simon.h...@gmail.com` on 24 Nov 2011 at 5:29

**Comment by fbacchella** [comment]
Done as a plugin: https://github.com/rrd4j/rrd4j-cassandra
