### ISSUE TITLE
RrdMongoDBBackendFactory doesn't work with driver for MongoDB 3.0

### ISSUE THREAD

**Issue by dsmolyarenko** [rrd4j/rrd4j#73]
RrdMongoDBBackendFactory doesn't work with driver for MongoDB 3.0

The method DBCollection.ensureIndex() which was marked as depricated has been removed from MongoDB 3.0
http://api.mongodb.org/java/2.13/com/mongodb/DBCollection.html#ensureIndex-com.mongodb.DBObject-

You have to use DBCollection.createIndex()
http://api.mongodb.org/java/3.0/com/mongodb/DBCollection.html#createIndex-com.mongodb.DBObject

**Comment by jochenberger** [comment]
In fact, {{DBCollection}} should not be used anymore. It has been superseded by {{com.mongodb.client.MongoCollection}}.

**Comment by analytically** [comment]
I'll fix this asap.

**Comment by freshteapot** [comment]
Any news? :D

**Comment by freshteapot** [comment]
- [ ] Upgrade the pom file.
```
org.mongodb:mongo-java-driver:3.4.0
```

- [ ] Use createIndex instead of ensureIndex.

```
rrdCollection.createIndex("path");
// rrdCollection.ensureIndex(new BasicDBObject("path", 1));
```

It is possible, more changes are needed.
I am very happy to help out, just not 100% sure how to go about setting up the project.

**Comment by fbacchella** [comment]
I don't have any knowledge about mongodb and no setup to test it. So even if I do the change you notified, I have no way to test if it works.

**Comment by fbacchella** [comment]
I tried to update it, see commit b770dcbb20ccf5f5a9f2b25246f458bee8ba6b62, but you should also have a look at the release notes. It's now possible to use the pool for it and connect different databases.
Tests are welcome.
