### ISSUE TITLE
The demo code not work with version : 2.2

### ISSUE THREAD

**Issue by cloudtrends** [rrd4j/rrd4j#76]
hi,

I use below code in my pom.xml

		<dependency>
		    <groupId>org.rrd4j</groupId>
		    <artifactId>rrd4j</artifactId>
		    <version>2.2</version>
		</dependency>

I found that the Variable class is missing when I try to compile demo code .

Error message shows that : can not find  org.rrd4j.data.Variable class .

**Comment by fbacchella** [comment]
git clone https://github.com/rrd4j/rrd4j.git
    git checkout tags/2.2
    mvn clean package
    java -cp target/rrd4j-2.2.jar org.rrd4j.demo.Demo

works. 

Anyway:

    $ find src -name Variable | wc -l 
           0

org.rrd4j.data.Variable is not part of the 2.2 branche
