### ISSUE TITLE
Adding multiple datasources to graph

### ISSUE THREAD

**Issue by tobyweston** [rrd4j/rrd4j#79]
If I have something like this

```scala
val graph = new RrdGraphDef()
graph.datasource("sensor1", path / s"temperature-1.rrd", "sensor1", AVERAGE)
graph.datasource("sensor1", path / s"temperature-2.rrd", "sensor1", AVERAGE)
graph.line("sensor1", green)
```
would you expect the graph to show two lines or one?

I'm trying to generate a single graph from seperate RRD files (with the same DS names in both).

I'm getting only one displayed, possibly because the name clashes (ie `sensor1`) but the API for adding a datasource doesn't have a restriction so I kind of thought it would allow me to keep adding RRD files and chart them together.

**Comment by fbacchella** [comment]
one name one plot. What more to say ?
