### ISSUE TITLE
Error with resolution in fetch requests

### ISSUE THREAD

**Issue by jlorenzocima** [rrd4j/rrd4j#80]
Hi Fabrice,
I doing some test with rrd4j and found an error with fetch when change resolution. I could not make it work, then check the same example with rrdtool and worked well.

Bellow copy the example using rrdtool and rr4j test cases with the corresponding outputs.

This is a error in rrd4j or I do some mistake?

I'm using: 
- rrd4j 2.2
- rrdtool 1.3.8
- CentOS 6.7
## rrdtool Test Case

rrdtool create test_rrdtool.rrd \
--start 920202900 \
--step 30 \
DS:counter:GAUGE:60:U:U \
DS:duration:GAUGE:60:U:U \
RRA:AVERAGE:0:1:20000 \
RRA:AVERAGE:0:5:200 

rrdtool update test_rrdtool.rrd -t counter:duration \
920202928:2:7 \
920202946:2:11 \
920202985:2:15 \
920203002:1:9 \
920203036:3:33 \
920203058:1:13 \
920203103:3:45 \
920203127:2:35 \
920203165:3:60 \
920203198:2:45 \
920203216:1:24 \
920203257:2:51 \
920203282:2:55 \
920203308:2:59 \
920203337:2:63 \
920203355:1:33 \
920203395:3:105 \
920203421:2:75 \
920203454:3:120 \
920203499:3:129 \
920203528:3:138
###### HERE USING DETAILED RRA

rrdtool fetch test_rrdtool.rrd AVERAGE --start 920202800 --end 920203565
                        counter            duration

 920202810: -nan -nan
 920202840: -nan -nan
 920202870: -nan -nan
 920202900: -nan -nan
 920202930: 2.0000000000e+00 7.2666666667e+00
 920202960: 2.0000000000e+00 1.2866666667e+01
 920202990: 1.8333333333e+00 1.4000000000e+01
 920203020: 2.2000000000e+00 2.3400000000e+01
 920203050: 2.0666666667e+00 2.3666666667e+01
 920203080: 2.4666666667e+00 3.6466666667e+01
 920203110: 2.7666666667e+00 4.2666666667e+01
 920203140: 2.4333333333e+00 4.5833333333e+01
 920203170: 2.8333333333e+00 5.7500000000e+01
 920203200: 1.9333333333e+00 4.3600000000e+01
 920203230: 1.4666666667e+00 3.6600000000e+01
 920203260: 2.0000000000e+00 5.1400000000e+01
 920203290: 2.0000000000e+00 5.6066666667e+01
 920203320: 2.0000000000e+00 6.0600000000e+01
 920203350: 1.5666666667e+00 5.0000000000e+01
 920203380: 2.6666666667e+00 9.3000000000e+01
 920203410: 2.5000000000e+00 9.0000000000e+01
 920203440: 2.6333333333e+00 1.0350000000e+02
 920203470: 3.0000000000e+00 1.2480000000e+02
 920203500: 3.0000000000e+00 1.2930000000e+02
 920203530: -nan -nan
 920203560: -nan -nan
 920203590: -nan -nan
###### HERE USE THE SUMMARY (SECOND) RRA

rrdtool fetch test_rrdtool.rrd AVERAGE --start 920202800 --end 920203565 -r 150
                        counter            duration

 920202900: -nan -nan
 920203050: 2.0200000000e+00 1.6240000000e+01
 920203200: 2.4866666667e+00 4.5213333333e+01
 920203350: 1.8066666667e+00 5.0933333333e+01
 920203500: 2.7600000000e+00 1.0812000000e+02
 920203650: -nan -nan
## Rrd4j Test Case

``` java
    @Test
    public void test_rrd4j() throws Exception {
        final String RRD_PATH = "test_rrd4j.rrd";
        //
        // create RRD definition
        RrdDef rrdDef = new RrdDef(RRD_PATH, 30);
        rrdDef.setStartTime(920202900);
        //
        // create datasources
        rrdDef.addDatasource("counter", DsType.GAUGE,60, Double.NaN, Double.NaN);
        rrdDef.addDatasource("duration", DsType.GAUGE,60, Double.NaN, Double.NaN);
        //
        // create archives
        rrdDef.addArchive(ConsolFun.AVERAGE, 0, 1, 20000);
        rrdDef.addArchive(ConsolFun.AVERAGE, 0, 5, 200);
        //
        // create database
        RrdDb rrdDb = new RrdDb(rrdDef);
        //
        // populate
        Sample sample = rrdDb.createSample();
        sample.setTime(920202928).setValue("counter", 2).setValue("duration", 7).update();
        sample.setTime(920202946).setValue("counter", 2).setValue("duration", 11).update();
        sample.setTime(920202985).setValue("counter", 2).setValue("duration", 15).update();
        sample.setTime(920203002).setValue("counter", 1).setValue("duration", 9).update();
        sample.setTime(920203036).setValue("counter", 3).setValue("duration", 33).update();
        sample.setTime(920203058).setValue("counter", 1).setValue("duration", 13).update();
        sample.setTime(920203103).setValue("counter", 3).setValue("duration", 45).update();
        sample.setTime(920203127).setValue("counter", 2).setValue("duration", 35).update();
        sample.setTime(920203165).setValue("counter", 3).setValue("duration", 60).update();
        sample.setTime(920203198).setValue("counter", 2).setValue("duration", 45).update();
        sample.setTime(920203216).setValue("counter", 1).setValue("duration", 24).update();
        sample.setTime(920203257).setValue("counter", 2).setValue("duration", 51).update();
        sample.setTime(920203282).setValue("counter", 2).setValue("duration", 55).update();
        sample.setTime(920203308).setValue("counter", 2).setValue("duration", 59).update();
        sample.setTime(920203337).setValue("counter", 2).setValue("duration", 63).update();
        sample.setTime(920203355).setValue("counter", 1).setValue("duration", 33).update();
        sample.setTime(920203395).setValue("counter", 3).setValue("duration", 105).update();
        sample.setTime(920203421).setValue("counter", 2).setValue("duration", 75).update();
        sample.setTime(920203454).setValue("counter", 3).setValue("duration", 120).update();
        sample.setTime(920203499).setValue("counter", 3).setValue("duration", 129).update();
        sample.setTime(920203528).setValue("counter", 3).setValue("duration", 138).update();
        //
        // fetch
        FetchRequest fetchRequest = rrdDb.createFetchRequest(ConsolFun.AVERAGE, 920202800, 920203565);
        FetchData fetchData = fetchRequest.fetchData();
        System.out.println("Without resolution \n"+fetchData.toString());
        fetchRequest = rrdDb.createFetchRequest(ConsolFun.AVERAGE, 920202800, 920203565, 150);
        fetchData = fetchRequest.fetchData();
        System.out.println("With resolution 150s \n"+fetchData.toString());
        //
        // close db
        rrdDb.close();

    }
```
###### HERE USING DETAILED RRA

Output Without resolution 
                      counter          duration

 920202780:               nan               nan
 920202810:               nan               nan
 920202840:               nan               nan
 920202870:               nan               nan
 920202900:               nan               nan
 920202930:  +2.0000000000E00  +7.2666666667E00
 920202960:  +2.0000000000E00  +1.2866666667E01
 920202990:  +1.8333333333E00  +1.4000000000E01
 920203020:  +2.2000000000E00  +2.3400000000E01
 920203050:  +2.0666666667E00  +2.3666666667E01
 920203080:  +2.4666666667E00  +3.6466666667E01
 920203110:  +2.7666666667E00  +4.2666666667E01
 920203140:  +2.4333333333E00  +4.5833333333E01
 920203170:  +2.8333333333E00  +5.7500000000E01
 920203200:  +1.9333333333E00  +4.3600000000E01
 920203230:  +1.4666666667E00  +3.6600000000E01
 920203260:  +2.0000000000E00  +5.1400000000E01
 920203290:  +2.0000000000E00  +5.6066666667E01
 920203320:  +2.0000000000E00  +6.0600000000E01
 920203350:  +1.5666666667E00  +5.0000000000E01
 920203380:  +2.6666666667E00  +9.3000000000E01
 920203410:  +2.5000000000E00  +9.0000000000E01
 920203440:  +2.6333333333E00  +1.0350000000E02
 920203470:  +3.0000000000E00  +1.2480000000E02
 920203500:  +3.0000000000E00  +1.2930000000E02
 920203530:               nan               nan
 920203560:               nan               nan
 920203590:               nan               nan
###### HERE NOT USE THE SUMMARY (SECOND) RRA AND I THINK THIS IS AN ERROR

Output With resolution 150s 
                      counter          duration

 920202780:               nan               nan
 920202810:               nan               nan
 920202840:               nan               nan
 920202870:               nan               nan
 920202900:               nan               nan
 920202930:  +2.0000000000E00  +7.2666666667E00
 920202960:  +2.0000000000E00  +1.2866666667E01
 920202990:  +1.8333333333E00  +1.4000000000E01
 920203020:  +2.2000000000E00  +2.3400000000E01
 920203050:  +2.0666666667E00  +2.3666666667E01
 920203080:  +2.4666666667E00  +3.6466666667E01
 920203110:  +2.7666666667E00  +4.2666666667E01
 920203140:  +2.4333333333E00  +4.5833333333E01
 920203170:  +2.8333333333E00  +5.7500000000E01
 920203200:  +1.9333333333E00  +4.3600000000E01
 920203230:  +1.4666666667E00  +3.6600000000E01
 920203260:  +2.0000000000E00  +5.1400000000E01
 920203290:  +2.0000000000E00  +5.6066666667E01
 920203320:  +2.0000000000E00  +6.0600000000E01
 920203350:  +1.5666666667E00  +5.0000000000E01
 920203380:  +2.6666666667E00  +9.3000000000E01
 920203410:  +2.5000000000E00  +9.0000000000E01
 920203440:  +2.6333333333E00  +1.0350000000E02
 920203470:  +3.0000000000E00  +1.2480000000E02
 920203500:  +3.0000000000E00  +1.2930000000E02
 920203530:               nan               nan
 920203560:               nan               nan
 920203590:               nan               nan

**Comment by fbacchella** [comment]
If rrd4j and rrdtool don't give the same output, I think it might be a bug. But I'm going to holiday tomorrow and I don't have time to check it better. I will be back in two weeks.

**Comment by jlorenzocima** [comment]
enjoy!! will see on you back

**Comment by fbacchella** [comment]
Ok, there is 2 bug in one.
The first is a real bug, the archive chosen is not the good one.
The second, the number of row returned is different from rrd. I'm not sure it I should correct it. I might be a mater of taste.

**Comment by fbacchella** [comment]
The first one is fixed in comit 593df53f806078c65b1ada4837d05e53b688e1ba

**Comment by jlorenzocima** [comment]
Fabrice Thank you for putting your time on this. One final question, this commit you going to integrate some release soon to have it available via maven?

**Comment by fbacchella** [comment]
I forgot it for 3.0, sorry. But there is snapshot available at https://oss.sonatype.org/content/repositories/snapshots/org/rrd4j/rrd4j/3.1-SNAPSHOT/.

**Comment by jlorenzocima** [comment]
Thx!!!
