### ISSUE TITLE
Bump to 2.2.2, 2.3 or 3.0?

### ISSUE THREAD

**Issue by ssbx** [rrd4j/rrd4j#92]
Hello,

There are some bug fixes from 2.2.1 which force me to use the 3.0-SNAPSHOT version (essentially, the temporary files used to generate the graphs not released). I would really appreciate a new release to let contributors contribute on the master branch without stressing me :).

For informations, what is the milestone you are waiting to accomplish for 3.0 release?

Regards.

**Comment by fbacchella** [comment]
I can prepare a 2.3.

For version 3 I want to wrote some backend that don't work any more at byte level, but on an higher abstraction level, that NewBackEnd branch is about.

**Comment by ssbx** [comment]
Ok. Would be nice to go to 2.3 for now.

**Comment by fbacchella** [comment]
I finally issued a version 3, they was a lot of change any way in rrd4j. The new backend will be for version 4.

It expect a more cloud friendly rrd4j with this.

**Comment by ssbx** [comment]
Thanks!
