### ISSUE TITLE
The file pom.xml doesn't contains the dependency for rrd4j ?

### ISSUE THREAD

**Issue by JeromeVi** [rrd4j/rrd4j#97]
I'm totally new with rrd4j and following the first steps I downloaded your pom.xml but at the beginning of the read.me it's say that we need to add: 
```
<dependency>
    <groupId>org.rrd4j</groupId>
    <artifactId>rrd4j</artifactId>
    <version>3.1</version>
</dependency>
```
So why there aren't those lines in the pom.xml ?

**Comment by fbacchella** [comment]
That's a maven question. Please learn how to use it.
