### ISSUE TITLE
Example of how to get values of given datasource in a given archive

### ISSUE THREAD

**Issue by youncta-dev** [rrd4j/rrd4j#99]
I have multiple data sources in the **rrd** database. I also have multiple archives, I would like to fetch an array with all values of a specific data source in a specific archive.

How can I accomplish this task?

**Comment by fbacchella** [comment]
Look at [Archive.html#getRobin(int)](http://rrd4j.org/site/apidocs/org/rrd4j/core/Archive.html#getRobin(int)), It will return a robin: [Robin.html#getValues()](http://rrd4j.org/site/apidocs/org/rrd4j/core/Robin.html#getValues())

But please don't open issues for support, there is a mailling list for that: [rrd4j-discuss](https://groups.google.com/forum/#!forum/rrd4j-discuss)
